// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Ros2Arrayspezifikationen6.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _FAST_DDS_GENERATED_CONVERSION_TESTS_MSG_ROS2ARRAYSPEZIFIKATIONEN6_H_
#define _FAST_DDS_GENERATED_CONVERSION_TESTS_MSG_ROS2ARRAYSPEZIFIKATIONEN6_H_

// #include "conversion_tests/msg/Ros2PrimitiveDatentypen.h"
#include "types/conversion_tests/msg/Ros2PrimitiveDatentypen/Ros2PrimitiveDatentypen.h"

#include <fastrtps/utils/fixed_size_string.hpp>

#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(ROS2ARRAYSPEZIFIKATIONEN6_SOURCE)
#define ROS2ARRAYSPEZIFIKATIONEN6_DllAPI __declspec( dllexport )
#else
#define ROS2ARRAYSPEZIFIKATIONEN6_DllAPI __declspec( dllimport )
#endif // ROS2ARRAYSPEZIFIKATIONEN6_SOURCE
#else
#define ROS2ARRAYSPEZIFIKATIONEN6_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define ROS2ARRAYSPEZIFIKATIONEN6_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
} // namespace fastcdr
} // namespace eprosima


namespace conversion_tests {
    namespace msg {
        /*!
         * @brief This class represents the structure Ros2Arrayspezifikationen6 defined by the user in the IDL file.
         * @ingroup Ros2Arrayspezifikationen6
         */
        class Ros2Arrayspezifikationen6
        {
        public:

            /*!
             * @brief Default constructor.
             */
            eProsima_user_DllExport Ros2Arrayspezifikationen6();

            /*!
             * @brief Default destructor.
             */
            eProsima_user_DllExport ~Ros2Arrayspezifikationen6();

            /*!
             * @brief Copy constructor.
             * @param x Reference to the object conversion_tests::msg::Ros2Arrayspezifikationen6 that will be copied.
             */
            eProsima_user_DllExport Ros2Arrayspezifikationen6(
                    const Ros2Arrayspezifikationen6& x);

            /*!
             * @brief Move constructor.
             * @param x Reference to the object conversion_tests::msg::Ros2Arrayspezifikationen6 that will be copied.
             */
            eProsima_user_DllExport Ros2Arrayspezifikationen6(
                    Ros2Arrayspezifikationen6&& x) noexcept;

            /*!
             * @brief Copy assignment.
             * @param x Reference to the object conversion_tests::msg::Ros2Arrayspezifikationen6 that will be copied.
             */
            eProsima_user_DllExport Ros2Arrayspezifikationen6& operator =(
                    const Ros2Arrayspezifikationen6& x);

            /*!
             * @brief Move assignment.
             * @param x Reference to the object conversion_tests::msg::Ros2Arrayspezifikationen6 that will be copied.
             */
            eProsima_user_DllExport Ros2Arrayspezifikationen6& operator =(
                    Ros2Arrayspezifikationen6&& x) noexcept;

            /*!
             * @brief Comparison operator.
             * @param x conversion_tests::msg::Ros2Arrayspezifikationen6 object to compare.
             */
            eProsima_user_DllExport bool operator ==(
                    const Ros2Arrayspezifikationen6& x) const;

            /*!
             * @brief Comparison operator.
             * @param x conversion_tests::msg::Ros2Arrayspezifikationen6 object to compare.
             */
            eProsima_user_DllExport bool operator !=(
                    const Ros2Arrayspezifikationen6& x) const;

            /*!
             * @brief This function copies the value in member absolute_reference
             * @param _absolute_reference New value to be copied in member absolute_reference
             */
            eProsima_user_DllExport void absolute_reference(
                    const std::vector<conversion_tests::msg::Ros2PrimitiveDatentypen>& _absolute_reference);

            /*!
             * @brief This function moves the value in member absolute_reference
             * @param _absolute_reference New value to be moved in member absolute_reference
             */
            eProsima_user_DllExport void absolute_reference(
                    std::vector<conversion_tests::msg::Ros2PrimitiveDatentypen>&& _absolute_reference);

            /*!
             * @brief This function returns a constant reference to member absolute_reference
             * @return Constant reference to member absolute_reference
             */
            eProsima_user_DllExport const std::vector<conversion_tests::msg::Ros2PrimitiveDatentypen>& absolute_reference() const;

            /*!
             * @brief This function returns a reference to member absolute_reference
             * @return Reference to member absolute_reference
             */
            eProsima_user_DllExport std::vector<conversion_tests::msg::Ros2PrimitiveDatentypen>& absolute_reference();
            /*!
             * @brief This function copies the value in member relative_reference
             * @param _relative_reference New value to be copied in member relative_reference
             */
            eProsima_user_DllExport void relative_reference(
                    const std::vector<conversion_tests::msg::Ros2PrimitiveDatentypen>& _relative_reference);

            /*!
             * @brief This function moves the value in member relative_reference
             * @param _relative_reference New value to be moved in member relative_reference
             */
            eProsima_user_DllExport void relative_reference(
                    std::vector<conversion_tests::msg::Ros2PrimitiveDatentypen>&& _relative_reference);

            /*!
             * @brief This function returns a constant reference to member relative_reference
             * @return Constant reference to member relative_reference
             */
            eProsima_user_DllExport const std::vector<conversion_tests::msg::Ros2PrimitiveDatentypen>& relative_reference() const;

            /*!
             * @brief This function returns a reference to member relative_reference
             * @return Reference to member relative_reference
             */
            eProsima_user_DllExport std::vector<conversion_tests::msg::Ros2PrimitiveDatentypen>& relative_reference();

            /*!
            * @brief This function returns the maximum serialized size of an object
            * depending on the buffer alignment.
            * @param current_alignment Buffer alignment.
            * @return Maximum serialized size.
            */
            eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
                    size_t current_alignment = 0);

            /*!
             * @brief This function returns the serialized size of a data depending on the buffer alignment.
             * @param data Data which is calculated its serialized size.
             * @param current_alignment Buffer alignment.
             * @return Serialized size.
             */
            eProsima_user_DllExport static size_t getCdrSerializedSize(
                    const conversion_tests::msg::Ros2Arrayspezifikationen6& data,
                    size_t current_alignment = 0);


            /*!
             * @brief This function serializes an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void serialize(
                    eprosima::fastcdr::Cdr& cdr) const;

            /*!
             * @brief This function deserializes an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void deserialize(
                    eprosima::fastcdr::Cdr& cdr);



            /*!
             * @brief This function returns the maximum serialized size of the Key of an object
             * depending on the buffer alignment.
             * @param current_alignment Buffer alignment.
             * @return Maximum serialized size.
             */
            eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(
                    size_t current_alignment = 0);

            /*!
             * @brief This function tells you if the Key has been defined for this type
             */
            eProsima_user_DllExport static bool isKeyDefined();

            /*!
             * @brief This function serializes the key members of an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void serializeKey(
                    eprosima::fastcdr::Cdr& cdr) const;

        private:

            std::vector<conversion_tests::msg::Ros2PrimitiveDatentypen> m_absolute_reference;
            std::vector<conversion_tests::msg::Ros2PrimitiveDatentypen> m_relative_reference;

        };
    } // namespace msg
} // namespace conversion_tests

#endif // _FAST_DDS_GENERATED_CONVERSION_TESTS_MSG_ROS2ARRAYSPEZIFIKATIONEN6_H_

